name: Deploy static site to Pages
on:
  push: {branches: [main]}
  workflow_dispatch:
permissions: {contents: read, pages: write, id-token: write}
concurrency: {group: pages, cancel-in-progress: true}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: {name: github-pages}
    steps:
      - uses: actions/checkout@v4
      # CNAME is already committed at repo root; no need to rewrite it here.
      - uses: actions/upload-pages-artifact@v3
        with: { path: "." }   # publish ROOT where index.html lives
      - id: deployment
        uses: actions/deploy-pages@v4
